services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    environment:
      - TF_ENABLE_ONEDNN_OPTS=1
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 4G